### ISSUE TITLE
gdalUtils not available for R 4.2.2

### ISSUE THREAD

**Issue by pauwiersma** [bermane/snowwarp#2]
Hi, thanks for the great package and documentation. I'm trying to get SnowWarp to run on Windows with R version 4.2.2. 
I could install the SnowWarp package, but when I ran process_snowwarp I got a warning that gdalUtils is not available for this version of R and an error saying there is no package called rgdal. 
I followed the instructions [here ](https://stackoverflow.com/questions/72703762/package-gdalutils-is-not-available-for-this-version-of-r-4-2-0) and installed gdalUtils through devtools::install_github. This seemed to work and it also installed rgdal, but then I ran process_snowwarp again and after two hours I got an error message saying gdalinfo could not be found in my QGIS folder, which I found surprising. 
Before risking to spend a lot of time on this, could you confirm with me that SnowWarp can run on R 4.2? And if yes, what is the best way to handle gdalUtils? Thanks!

```
> process_snowwarp(folder = "D:/PhDs/pau.wiersma_at_unil.ch/Snowmaps/SnowWarp/SnowWarpTest/", years = 2004:2005, cpus = 8, otb_dir = "D:/PhDs/pau.wiersma_at_unil.ch/Random/OTB-8.1.1-Win64/",max_ram = 20000)
Installing package into ‘C:/Users/PWiersma/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘gdalUtils’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
[1] "Processing of Landsat tile 1 started at 2023-02-07 17:11:50."
Error in { : task 1 failed - "there is no package called 'rgdal'"
```

```
> process_snowwarp(folder = "D:/PhDs/pau.wiersma_at_unil.ch/Snowmaps/SnowWarp/SnowWarpTest/", years = 2004:2005, cpus = 8, otb_dir = "D:/PhDs/pau.wiersma_at_unil.ch/Random/OTB-8.1.1-Win64/",max_ram = 40000)
[1] "Processing of Landsat tile 1 started at 2023-02-08 09:03:20."
Error in FUN(X[[i]], ...) : 
  '"C:\Program Files\QGIS 3.22.16\apps\gdal\share\bash-completion\completions\gdalinfo"' not found
```

**Comment by bermane** [comment]
Hi,

I think the issue you are encountering is that R is not able to find a valid installation of gdal for use with the gdalUtils package. Please see the thread below to install GDAL using OSGeo4W64 and ensure that gdalUtils references the new installation instead of looking for GDAL in QGIS. I hope this helps!

Cheers,

Ethan
